name: Build Project with MinGW and Vulkan SDK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install MinGW
      run: |
        choco install mingw

    - name: Download Vulkan SDK
      run: |
        $VulkanSdkUrl = "https://sdk.lunarg.com/sdk/download/1.3.239.0/windows/vulkansdk-macos-x.x.x.x.tar.gz"
        $VulkanSdkZip = "vulkan-sdk.zip"
        
        Invoke-WebRequest -Uri $VulkanSdkUrl -OutFile $VulkanSdkZip
        Expand-Archive -Path $VulkanSdkZip -DestinationPath $env:ProgramFiles\Vulkan
        Remove-Item $VulkanSdkZip

    - name: Set Vulkan environment variables
      run: |
        $env:VULKAN_SDK = "${env:ProgramFiles}\Vulkan\1.3.239.0\"
        [System.Environment]::SetEnvironmentVariable("VULKAN_SDK", $env:VULKAN_SDK, [System.EnvironmentVariableTarget]::Machine)
        [System.Environment]::SetEnvironmentVariable("PATH", "$env:PATH;$env:VULKAN_SDK\Bin;$env:VULKAN_SDK\Lib", [System.EnvironmentVariableTarget]::Machine)

    - name: Install CMake via Chocolatey
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'

    - name: Configure CMake project with MinGW
      run: |
        cmake -S . -B build -G "MinGW Makefiles"
        cmake --build build --config Release

    - name: Run tests (optional)
      run: |
        cmake --build build --config Release --target test
