name: Build Engine

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        include:
          - os: windows-latest
            cmake_generator: "Visual Studio 17 2022"
          - os: ubuntu-latest
            cmake_generator: "Unix Makefiles"

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install Linux Dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libvulkan-dev vulkan-validationlayers-dev xorg-dev libglu1-mesa-dev

    - name: Install Windows Dependencies
      if: runner.os == 'Windows'
      run: |
        # O Vulkan SDK será instalado automaticamente pelo próprio CMake

    - name: Configure CMake
      run: |
        cmake -B build -G "${{ matrix.cmake_generator }}" -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: |
        cmake --build build --config Release

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: vulkan-engine-${{ runner.os }}
        path: |
          build/VulkanEngine*
          build/engine/