name: Build Project with MinGW

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up MinGW
      run: |
        choco install mingw

    - name: Set up CMake
      uses: actions/setup-cmake@v2

    - name: Configure CMake project with MinGW
      run: |
        cmake -S . -B build -G "MinGW Makefiles"
        cmake --build build --config Release

    - name: Run tests (optional)
      run: |
        cmake --build build --config Release --target test
