name: Build Project with MinGW and Vulkan SDK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Prepare Vulkan SDK
      uses: humbletim/setup-vulkan-sdk@v1.2.0
      with:
        vulkan-query-version: 1.3.296.0
        vulkan-components: Vulkan-Headers, Vulkan-Loader
        vulkan-use-cache: true

    - name: Install MinGW
      run: |
        choco install mingw

    - name: Install CMake manually
      run: |
        # Baixa o instalador do CMake
        Invoke-WebRequest -Uri https://github.com/Kitware/CMake/releases/download/v3.31.1/cmake-3.31.1-windows-x86_64.msi
        # Instala o CMake silenciosamente
        Start-Process msiexec.exe -ArgumentList '/i', 'cmake.msi', '/quiet', '/norestart' -NoNewWindow -Wait
        # Remove o instalador após a instalação
        Remove-Item -Force cmake.msi

    - name: Configure CMake project with MinGW
      run: |
        cmake -S . -B build -G "MinGW Makefiles"
        cmake --build build --config Release

    - name: Package Release Artifacts
      run: |
        mkdir -p release
        cp -r build/* release/

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: release/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}