name: Build VulkanEngine

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2022
    
    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1
      with:
        cmake-version: '3.20.0'

    - name: Set up Vulkan SDK
      run: |
        $env:VULKAN_SDK = "C:\VulkanSDK\1.2.182.0"
        $env:Path = "$env:VULKAN_SDK\bin;$env:Path"
        Write-Host "Vulkan SDK Path: $env:VULKAN_SDK"
        
    - name: Configure CMake
      run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64

    - name: Build with CMake
      run: cmake --build build --config Release --target all

    - name: Run tests
      run: |
        # Se você tiver testes, pode rodá-los aqui
        echo "Running tests (se houver)"
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: VulkanEngine-build
        path: build
