name: Build Project with MinGW and Vulkan SDK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install MinGW
      run: |
        choco install mingw

    - name: Download Vulkan SDK Installer
      run: |
        Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/1.3.296.0/windows/VulkanSDK-1.3.296.0-Installer.exe" -OutFile "VulkanSDK-Installer.exe"

    - name: Install Vulkan SDK
      run: |
        Start-Process -FilePath "VulkanSDK-Installer.exe" -ArgumentList "/S" -Wait

    - name: Install CMake via Chocolatey
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'

    - name: Set Vulkan environment variables
      run: |
        $VulkanSdkPath = "${env:ProgramFiles}\Vulkan\SDK\1.3.296.0"  # Ajuste para a versão instalada
        [System.Environment]::SetEnvironmentVariable("VULKAN_SDK", $VulkanSdkPath, [System.EnvironmentVariableTarget]::Machine)
        [System.Environment]::SetEnvironmentVariable("PATH", "$env:PATH;$VulkanSdkPath\Bin;$VulkanSdkPath\Lib", [System.EnvironmentVariableTarget]::Machine)

    - name: Configure CMake project with MinGW
      run: |
        cmake -S . -B build -G "MinGW Makefiles"
        cmake --build build --config Release

    - name: Run tests (optional)
      run: |
        cmake --build build --config Release --target test
