name: Build VulkanEngine

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        compiler: [gcc, clang]
        exclude:
          - os: macos-latest
            compiler: gcc

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Vulkan SDK
      if: runner.os == 'Linux' || runner.os == 'macOS'
      run: |
        sudo apt-get update
        sudo apt-get install -y vulkan-sdk libvulkan-dev
      shell: bash

    - name: Set up Vulkan SDK for Windows
      if: runner.os == 'Windows'
      env:
        VK_SDK_PATH: 'C:/VulkanSDK/1.3.250.0'
      run: |
        echo "Setting Vulkan SDK for Windows"
        echo "VULKAN_SDK=${{env.VK_SDK_PATH}}" >> $env:GITHUB_ENV

    - name: Install dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libx11-dev libgl1-mesa-dev libboost-all-dev cmake g++ gcc
      shell: bash

    - name: Install dependencies for macOS
      if: runner.os == 'macOS'
      run: |
        brew update
        brew install boost cmake
      shell: bash

    - name: Install dependencies for Windows
      if: runner.os == 'Windows'
      run: |
        choco install cmake boost
      shell: bash

    - name: Configure CMake
      run: |
        cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
      shell: bash

    - name: Build with CMake
      run: |
        cmake --build build --config Release
      shell: bash