name: Build Project

on:
  pull_request:
  workflow_dispatch:
  push:
    tags: ['*']

jobs:
  build-linux:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup dependencies in Arch Linux
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm \
            base-devel \
            cmake \
            vulkan-devel \
            boost \
            glslang \
            libxrandr \
            libxinerama \
            libxcursor \
            libxi \
            libx11 \
            mesa \
            git \
            zip \
            glm \
            glfw-x11

      - name: Cache CMake build
        uses: actions/cache@v3
        with:
          path: |
            build/
            ~/.cache/
          key: ${{ runner.os }}-cmake-archlinux-${{ hashFiles('**/*.cpp', '**/*.h', '**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-cmake-archlinux-

      - name: Build project (Linux)
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release

      - name: Package release (Linux)
        run: |
          mkdir release
          cp -r build/* release/
          zip -r VulkanEngine-linux.zip release/

      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: VulkanEngine-linux-build
          path: |
            VulkanEngine-linux.zip

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install MinGW and dependencies
        run: |
          choco install -y mingw --version=13.2.0
          echo "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Cache Vulkan SDK
        uses: actions/cache@v3
        id: cache-vulkan
        with:
          path: |
            ${{ env.TEMP }}\VulkanSDK
            C:\VulkanSDK
          key: ${{ runner.os }}-vulkan-1.4.309.0

      - name: Install Vulkan SDK (Windows)
        if: steps.cache-vulkan.outputs.cache-hit != 'true'
        run: |
          $vulkanUrl = "https://sdk.lunarg.com/sdk/download/1.4.309.0/windows/VulkanSDK-1.4.309.0-Installer.exe"
          $installerPath = "$env:TEMP\VulkanSDK-Installer.exe"
          Invoke-WebRequest -Uri $vulkanUrl -OutFile $installerPath
          Start-Process -FilePath $installerPath -Args "--accept-licenses --default-answer --confirm-command install" -Wait
          
      - name: Setup Vulkan paths
        run: |
          [Environment]::SetEnvironmentVariable("VULKAN_SDK", "$env:VULKAN_SDK", [EnvironmentVariableTarget]::Machine)
          echo "VULKAN_SDK=$env:VULKAN_SDK" >> $env:GITHUB_ENV
          echo "$env:VULKAN_SDK\Bin" >> $env:GITHUB_PATH

      - name: Install GLM Library
        run: |
          mkdir -p include
          Invoke-WebRequest -Uri "https://github.com/g-truc/glm/releases/download/0.9.9.8/glm-0.9.9.8.zip" -OutFile "glm.zip"
          Expand-Archive -Path "glm.zip" -DestinationPath "include"
          echo "GLM_INCLUDE_DIR=${{ github.workspace }}\include\glm" >> $env:GITHUB_ENV

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.14'

      - name: Cache CMake build
        uses: actions/cache@v3
        with:
          path: |
            build/
            ~\.cmake\
          key: ${{ runner.os }}-cmake-mingw-${{ hashFiles('**/*.cpp', '**/*.h', '**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-cmake-mingw-

       # Build para Windows
      - name: Build project (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release

      - name: Package release (Windows)
        run: |
          mkdir release
          xcopy /E /I build\* release\
          7z a VulkanEngine-windows.zip ./release/*

      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: VulkanEngine-windows-build
          path: |
            VulkanEngine-windows.zip
