name: Build Project with MinGW and Vulkan SDK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Vulkan SDK on C: drive
      run: |
        # Baixar e instalar o Vulkan SDK diretamente no disco C
        $vulkanUrl = "https://vulkan.lunarg.com/sdk/home"
        $vulkanInstallerPath = "C:/vulkan-sdk-installer.exe"
        Invoke-WebRequest -Uri $vulkanUrl -OutFile $vulkanInstallerPath

        # Executa a instalação
        Start-Process $vulkanInstallerPath -ArgumentList "/quiet /install C:\VulkanSDK" -NoNewWindow -Wait

        # Verifica se a instalação foi bem-sucedida
        if (Test-Path "C:/VulkanSDK") {
          Write-Host "Vulkan SDK instalado com sucesso no C:/VulkanSDK"
        } else {
          Write-Host "Falha na instalação do Vulkan SDK"
          exit 1
        }

    - name: Install MinGW
      run: |
        choco install mingw

    - name: Install CMake manually
      run: |
        # Baixa o instalador do CMake
        Invoke-WebRequest -Uri https://github.com/Kitware/CMake/releases/download/v3.31.1/cmake-3.31.1-windows-x86_64.msi -OutFile cmake-3.31.1-windows-x86_64.msi

        # Verifica se o arquivo foi baixado corretamente
        if (Test-Path cmake-3.31.1-windows-x86_64.msi) {
          # Instala o CMake silenciosamente
          Start-Process msiexec.exe -ArgumentList '/i', 'cmake-3.31.1-windows-x86_64.msi', '/quiet', '/norestart' -NoNewWindow -Wait
          # Remove o instalador após a instalação
          Remove-Item -Force cmake-3.31.1-windows-x86_64.msi
        } else {
          Write-Host "Falha ao baixar o instalador do CMake."
          exit 1
        }

    - name: Configure CMake project with MinGW
      run: |
        cmake -S . -B build -G "MinGW Makefiles"
        cmake --build build --config Release

    - name: Compile Shaders with Vulkan SDK
      run: |
        # Caminho para o compilador de shaders (glslc.exe)
        $glslcPath = "C:/VulkanSDK/1.3.296.0/Bin/glslc.exe"

        # Verifica se o glslc.exe está disponível
        if (Test-Path $glslcPath) {
          # Compila o shader
          & $glslcPath "D:/a/VulkanEngine/VulkanEngine/shaders/fragment.frag" -o "D:/a/VulkanEngine/VulkanEngine/build/shaders/fragment.spv"
        } else {
          Write-Host "glslc.exe não encontrado. Verifique a instalação do Vulkan SDK."
          exit 1
        }

    - name: Package Release Artifacts
      run: |
        mkdir -p release
        cp -r build/* release/

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: release/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}